<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.mycompany</groupId>
        <artifactId>battleship</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <artifactId>battleship-client</artifactId>
    <packaging>jar</packaging>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <javafx.version>21.0.1</javafx.version>
        <exec.mainClass>com.mycompany.battleship.client.gui.SplashGUI</exec.mainClass>
    </properties>

    <dependencies>
        <!-- Module Common dùng chung giữa Client và Server -->
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>battleship-common</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- Thư viện JavaFX Controls (Button, Label, TextField...) -->
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>${javafx.version}</version>
        </dependency>

        <!-- Thư viện JavaFX FXML -->
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>${javafx.version}</version>
        </dependency>
        
        <!-- Thư viện JavaFX Media (Âm thanh, Nhạc nền) -->
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-media</artifactId>
            <version>${javafx.version}</version>
        </dependency>
    </dependencies>
        
    <build>
        <plugins>
            <!-- Plugin hỗ trợ chạy trực tiếp JavaFX trên Maven -->
            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>0.0.8</version>
                <configuration>
                    <mainClass>com.mycompany.battleship.client.gui.SplashGUI</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>